name: Checks

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    types: [opened, synchronize, reopened]

jobs:
  setup:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci

  build:
    runs-on: ubuntu-latest

    needs: setup

    steps:
      - run: npm run build

  lint:
    runs-on: ubuntu-latest

    needs: setup

    steps:
      - run: npm run lint

  test:
    runs-on: ubuntu-latest

    needs: setup

    steps:
      - run: npm test
